### ISSUE TITLE
Cannot open an excel file

### ISSUE THREAD

**Issue by fkmuthoni** [SCiO-systems/eiaspatial-notebook#1]
I uploaded an excel file but I got an error that exl is not UTF-8 encoded.

**Comment by sotkonstantinidis** [comment]
@fkmuthoni we are currently investigationg the issue, it would be really helpfull if could have an example excel file to recreate the issues.

**Comment by agelosnm** [comment]
@fkmuthoni I reproduce the issue by using a dummy excel file. I installed [jupyterlab-spreadsheet](https://github.com/quigleyj97/jupyterlab-spreadsheet) extension and now the excel files are opening.

Please note the file formats that this plugin supports and check.

**Comment by sotkonstantinidis** [comment]
For reference: 
" jupyterlab-spreadsheet supports XLS, XLSX, ODS, and CSV files, and allows for basic formatting"
