### ISSUE TITLE
Constant interruptions from server unavailable message

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#10]
Wherever I am working in Nairobi I get the same message almost every minute, making working on the CGlabs server very irritating.

Server unavailable or unreachable
Your server at /user/p.steward@cgiar.org/ is not running. Would you like to restart it?

My connection is good enough, so why am I getting this issue? other colleagues report the same problem.

**Comment by sotkonstantinidis** [comment]
@peetmate this is something that usually pops-up whenever the internet connection is unstable (not slow, but unstable). Are you connected through cable or are you using WiFi ?

**Comment by peetmate** [comment]
I am using WiFi, I do not have a cable.

**Comment by peetmate** [comment]
It is popping up several times per minute

**Comment by agelosnm** [comment]
issue resolved by user using ethernet cable for his connection
