### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#11]
I set up a second server, but it stopped working soon after creation.

I get "Service Unavailable" message when trying to access either of the below links.

https://eia.scio.services:18002/hub/home
https://eia.scio.services:18002/hub/spawn/p.steward@cgiar.org/Pete2

**Comment by peetmate** [comment]
services appears to have resumed, what was causing the issue?

**Comment by peetmate** [comment]
The kernels I was running seem to have disappeared without saving

**Comment by peetmate** [comment]
I had a situation where the file browser was frozen, but the console was still running

**Comment by sotkonstantinidis** [comment]
@peetmate service is up; the deployment of the updated image created the issue. 
In general, even if the browser freezes the actual execution of the kernel continues.
