### ISSUE TITLE
Unresponsive R console - Different issue

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#13]
https://eia.scio.services:18002/user/p.steward@cgiar.org/Pete2/

I went to have lunch when I returned my R console has become unresponsive, I just get [*] when I try and run a line and nothing happens.

It says R|Connecting at the bottom of my screen

**Comment by peetmate** [comment]
Error messages: invalid response: 405 method not allowed

and 

JupyterHub server hub no longer runnint at.....restart the server at....

**Comment by peetmate** [comment]
I gave up, and restarting. However, restarting my servers is taking a long time >5min

**Comment by peetmate** [comment]
Got spawn failed message. Restarted only opening one server. That seem to work..

**Comment by sotkonstantinidis** [comment]
@peetmate the overall delay is due to the insertion of new libraries (those from #9 ), now you should be ok.
