### ISSUE TITLE
Kernal will not connect to R

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#16]
I was doing OK working on CGlabs this morning, but stepped away for lunch when I came back the kernal for my console said R|Connecting......this does not change with time. If I click on R|Connnecting and select an R kernal I get a 405 Method not allowed error.

**Comment by peetmate** [comment]
If I close all the active kernals and open a console for an editor, I still have the same issue R|Connecting and a kernal stick on [*] when any line is executed

**Comment by peetmate** [comment]
JupyterHub server no longer running at /user/p.steward@cgiar.org/api/contents/atlas/solutions/analogues/R/2_Analogues_Analysis.R. Restart the server at https://eia.scio.services:18002/hub/spawn/p.steward@cgiar.org

**Comment by peetmate** [comment]
what happened to my server? Why is being closed down?

**Comment by sotkonstantinidis** [comment]
@peetmate after a certain period of inactivity (where inactivity means a period of time where the cpu cycles are under a specific %), the system stops the server to deallocate the resources. Everything written in your filesystem persists.

**Comment by peetmate** [comment]
I was only away for lunch! how quickly are the servers shut down?

**Comment by agelosnm** [comment]
Changed cull policy on JupyterHub
