### ISSUE TITLE
Cannot open terminal + Github repo remote is not configured

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#17]
1) Github will not push, it was working previously
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20173624/181049227-d25fa31c-4aa8-4fb9-bcda-fa67cebe3a5f.png)

2) there appears to be no remote set
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20173624/181049028-bef85c6d-81cc-487a-a175-bcc9d0eb6852.png)

3) I cannot add a remote as it already exists
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/20173624/181049346-51415b1f-3e1c-42d3-b527-f21b1c1af066.png)

4) I cannot open a terminal

**Comment by peetmate** [comment]
I had to shut down the server and start again, this seems to have fixed the terminal issue

**Comment by peetmate** [comment]
It has also fixed the github issue

**Comment by agelosnm** [comment]
I suppose that the issue occurs due to the fact that you tried to use git commands in a directory where no any git repo exists (atlas/solutions/metadata).
