### ISSUE TITLE
Cannot access File menu to restart frozen notebook

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#19]
My notebook appears to be frozen, I cannot access the file menu to restart the server. Refreshing the browser does nothing.

How can I resolve this situation?

**Comment by peetmate** [comment]
on a browser refresh it gave a new seconds to reach the hubcontrol panel before freezing up again, I have restarted my server

**Comment by peetmate** [comment]
hmmm a browser refresh seems to have fixed the issue

**Comment by peetmate** [comment]
my tabs keep freezing up, I can work in the one that is active but I cannot switch to a new one or access the notebook menus

**Comment by peetmate** [comment]
A system restart seems to have fixed whatever issue the notebook was having

**Comment by agelosnm** [comment]
connectivity issues
