### ISSUE TITLE
sp::CRS function not working

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#20]
Simple command:
`Crs    <- sp::CRS("+init=epsg:4326") # proj4string of coords`

gives an error and returns `NA` 

suggests an issue with the spatial packages/tools in Rstudio

**Comment by peetmate** [comment]
This is a problem as it stopping a major analysis I need to run.

**Comment by peetmate** [comment]
![image](https://user-images.githubusercontent.com/20173624/196982537-d5f2ce36-f5a7-4d97-9f39-37673710fb62.png)

This is the correct behaviour

**Comment by agelosnm** [comment]
https://github.com/jhollist/elevatr/issues/48#issuecomment-1059802332
