### ISSUE TITLE
File compression not working when using base save function and an array?

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#21]
https://eia-cglabssupport.slack.com/archives/C03RFLA6AKX/p1666609001486649

**Comment by agelosnm** [comment]
Please provide a description of the bug here too as the slack link you have posted cannot be seen.

**Comment by agelosnm** [comment]
Issue occured to user as the code that was being was under R version 4.2.1 whereas eiaspatial-notebooks supports 4.1.3
