### ISSUE TITLE
Packages required

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#3]
Hmisc
circlize
diagis
dismo
ggnewscale
lmerTest
lme4
metafor
metan
ncdf4
pbapply
raster
rgeos
rworldmap
sp
spatstat.geom
terra

**Comment by agelosnm** [comment]
@peetmate The above R packages have been installed. Please check and revert.

**Comment by agelosnm** [comment]
@peetmate Will proceed with the installation of the mentioned packages. Please note that  "broom" package is already installed.

**Comment by egbendito** [comment]
I am assuming both were spelling mistakes. For "doSNOW" I will refer to @peetmate to confirm

**Comment by agelosnm** [comment]
@egbendito Noted! In the meantime, please note that the rest of the packages have been installed and are available for use.

**Comment by agelosnm** [comment]
@peetmate any updates regarding the above comments?

**Comment by sotkonstantinidis** [comment]
@peetmate @egbendito  we will install "doSNOW" & "shapefiles" and close the issue. If we need anything else we can re-open the issue.

**Comment by agelosnm** [comment]
Both aforementioned packages are now installed

**Comment by egbendito** [comment]
Can we add a couple of python packages to the requirements?

I would like to add:

`xarray`
`cdsapi`

Thanks

**Comment by agelosnm** [comment]
@egbendito requested packages have been installed.
Please open new issues for such requests in the future as it is easier for us to track the changes. 

Thank you!
