### ISSUE TITLE
NetCDF Operators Library

### ISSUE THREAD

**Issue by egbendito** [SCiO-systems/eiaspatial-notebook#4]
I would like to have access to the [NetCDF Operators (NCO)](http://nco.sourceforge.net/) to handle weather and climate files. These are binaries installed at the OS. The installer is accessible here: [https://github.com/nco/nco](https://github.com/nco/nco). Is it possible to add it to Jupyter Lab?

**Comment by agelosnm** [comment]
@egbendito We installed NCO library using the relevant instructions provided from the official NCO page (http://nco.sourceforge.net/) for the Ubuntu OS since the image is using this as its base OS.

Please check and revert.

**Comment by egbendito** [comment]
Thanks @agelosnm It is installed and I can use the NCO binaries.

**Comment by sotkonstantinidis** [comment]
@egbendito nice! I will close the issue!
