### ISSUE TITLE
Interaction Rmarkdown/Shiny Environment needed

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#5]
A lot of my work involves make interactive rmarkdown scripts in RStudio, I need to be able to run and interact with these scripts in CGlabs.

**Comment by sotkonstantinidis** [comment]
@peetmate We are in process of integration RStudio to the infrastructure. Thus you will be able to use shiny and R Markdown as usual.

**Comment by agelosnm** [comment]
Rstudio intergration has been completed. General configuration is mssing and needs to be applied.
