### ISSUE TITLE
Data deleted in volume

### ISSUE THREAD

**Issue by egbendito** [SCiO-systems/eiaspatial-notebook#6]
Hi, I have noticed that due to the update/changes in the volume permissions some of the data has been deleted or is missing. This has also been rolled-down to user directories, as I can't find some of the scripts and data that I had under my user tree.
Was this expected?

**Comment by sotkonstantinidis** [comment]
@egbendito Last week we had a scheduled upgrade of the infrstructure and your data haven't been loaded to your workspace. The issue has been resolved, and now you should be able to have access to all your data. 

Please let me know if eveything is in place to close the issue

**Comment by egbendito** [comment]
Thanks @sotkonstantinidis the data is restored in my user tree

**Comment by egbendito** [comment]
@sotkonstantinidis I just realized that the restored data is unwrittable (has GID permissions that I cannot access). I can copy the data to solve this, but maybe there is a easier option?

**Comment by agelosnm** [comment]
@egbendito could you please check now if the issue with GID is resolved?
