### ISSUE TITLE
CG Labs down?

### ISSUE THREAD

**Issue by egbendito** [SCiO-systems/eiaspatial-notebook#7]
Hi @SCiO-systems,

I am trying to access CG Labs through Auth0 but get this error message:
![image](https://user-images.githubusercontent.com/52239752/174734097-632a81bc-2645-4648-b9e3-74cf2e1cffc1.png)

Also when trying to log in through the CG Labs login page [cglabs.eia.scio.services](https://cglabs.eia.scio.services/) and recover my password is not really working for me.

**Comment by sotkonstantinidis** [comment]
Hi @egbendito ! 
Can you please check again?

**Comment by egbendito** [comment]
I just logged in! Thank you @sotkonstantinidis
