### ISSUE TITLE
Uploading data

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#8]
It is extremely tedious, slow and trying to upload data into CGlabs. Most times I try to upload a file the connection breaks and an incomplete file is created.

When is the onedrive functionality going to be implemented?

**Comment by peetmate** [comment]
This does not appear to be a problem for a colleague working from the university of Wageningen with an excellent connection, but for people working from home in Africa upload bandwidth is a serious bottleneck

**Comment by sotkonstantinidis** [comment]
@peetmate for now the problem can be circumvented using libraries from #9 . A more general solution is part of 2022's Roadmap, but we do not expect to have it before the end of the year

**Comment by peetmate** [comment]
The upload system needs to be more stable for users with low bandwidth.

**Comment by sotkonstantinidis** [comment]
@peetmate part of the planned solution is to allow auto-resuming of the uploading process, thus regardless of the network instability, the process will be able to continue
