### ISSUE TITLE
R packages to access cloud storage

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#9]
To facilitate access and download from cloud storage can we have r-packages to interface with iCloud, Dropbox and onedrive installed?

https://github.com/karthik/rdrop2
https://cran.r-project.org/web/packages/Microsoft365R/vignettes/od_sp.html

I couldn't find anything for apple icloud, so perhaps there isn't a package for that?

**Comment by peetmate** [comment]
also a package to connect to AWS S3 bucket:
https://cran.r-project.org/web/packages/aws.s3/readme/README.html

**Comment by sotkonstantinidis** [comment]
@peetmate we searched also, but couldn't find something for icloud

**Comment by peetmate** [comment]
Edu mentioned he uses the packages googleCloudStorageR

**Comment by agelosnm** [comment]
mentioned packages have been installed
